kind: pipeline
type: docker
name: test

steps:
  - name: unit-test
    image: golang:1.13
    commands:
      - go mod download
      - go test -coverprofile=coverage.out ./...

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
  # tag is in .tag file (comman separated).
  - name: docker
    image: plugins/docker
    settings:
      username: hanjunlee
      password:
        from_secret: docker_password
      repo: hanjunlee/ext-authz
      auto_tag: true

trigger:
  target:
    - production
